
function Home() {

    return(
        <div>
            Home
                        <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>            <p>stink</p>
        </div>
    )
}

export default Home;